"""Add login,logout and sign up

Revision ID: 51795d07323f
Revises: 0a3627544036
Create Date: 2019-11-21 16:31:51.997175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51795d07323f'
down_revision = '0a3627544036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
